name: E2E tests - Selenium + Chrome

on:
  pull_request:
    branches:
      - main
      - dev # as a test
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: Install modules
        run: npm install
      - name: Install tsc
        run: npm install -g typescript
      - name: Install chrome
        uses: browser-actions/setup-chrome@v1
      - name: Check chrome version
        run: chrome --version
      - name: Run E2E tests
        uses: BerniWittmann/background-server-action@v1
        with:
          command: E2E_USER=${{ secrets.E2E_USER }} E2E_PASS=${{ secrets.E2E_PASS }} ./run-selenium.sh
          start: npm run dev # Run the UI in dev mode, with test headers
          wait-on: "http://localhost:3000"
